drone_node:
  ros__parameters:
    split_mode: true
    tx_device: "/tmp/ttyV0"
    rx_device: "/tmp/ttyV1"
    baudrate: 9600
    channel: 1
    level: 4
    diagnostic: false
    timeout: 0.5
    # TDMA config
    num_slots: 2
    my_slot: 0
    slot_duration_sec: 25
    guard_ms: 1000
    sync_delay: 5
    estiamted_prop_delay: 0